baseURL = 'https://yoursite.example.com/'
languageCode = "en-us"
title = 'Next Generation Doulas'
[params]
  AuthorName = 'Zoe Sullivan'
  GitHubUser = 'zothsu'
  
[permalinks]
  posts = '/:year/:month/:title/'


# what are some hugo front matter codes I can use for my front matter? Does this even need to be declared here or should i move it to the archtypes/default folder?
[frontmatter]
  date = ['year', 'publishDate', 'pubdate', 'lastmod', 'modified']
  lastmod = [':git', 'lastmod', 'modified', 'date', 'publishDate']
